# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseOrganization(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Organization']] = 'Organization'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.OrganizationActions[_PrismaModelT]':
        from .client import get_client

        return actions.OrganizationActions[_PrismaModelT](client or get_client(), cls)


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseVendor(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Vendor']] = 'Vendor'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.VendorActions[_PrismaModelT]':
        from .client import get_client

        return actions.VendorActions[_PrismaModelT](client or get_client(), cls)


class BaseProcurementRequest(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ProcurementRequest']] = 'ProcurementRequest'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProcurementRequestActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProcurementRequestActions[_PrismaModelT](client or get_client(), cls)


class BaseQuote(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Quote']] = 'Quote'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.QuoteActions[_PrismaModelT]':
        from .client import get_client

        return actions.QuoteActions[_PrismaModelT](client or get_client(), cls)


class BasePayment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Payment']] = 'Payment'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PaymentActions[_PrismaModelT]':
        from .client import get_client

        return actions.PaymentActions[_PrismaModelT](client or get_client(), cls)


class BaseAuditLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuditLog']] = 'AuditLog'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuditLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuditLogActions[_PrismaModelT](client or get_client(), cls)


class BaseEmailThread(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EmailThread']] = 'EmailThread'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EmailThreadActions[_PrismaModelT]':
        from .client import get_client

        return actions.EmailThreadActions[_PrismaModelT](client or get_client(), cls)


class BaseEmailMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EmailMessage']] = 'EmailMessage'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EmailMessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.EmailMessageActions[_PrismaModelT](client or get_client(), cls)


class BaseWorkflowExecution(_PrismaModel):
    __prisma_model__: ClassVar[Literal['WorkflowExecution']] = 'WorkflowExecution'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.WorkflowExecutionActions[_PrismaModelT]':
        from .client import get_client

        return actions.WorkflowExecutionActions[_PrismaModelT](client or get_client(), cls)


