# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/home/aparna/Desktop/supplygraph_mvp/apps/ai-service/schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'debian-openssl-3.0.x': '/home/aparna/.cache/prisma-python/binaries/5.17.0/393aa359c9ad4a4bb28630fb5613f9c281cde053/node_modules/prisma/query-engine-debian-openssl-3.0.x'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    organization: 'actions.OrganizationActions[models.Organization]'
    user: 'actions.UserActions[models.User]'
    vendor: 'actions.VendorActions[models.Vendor]'
    procurementrequest: 'actions.ProcurementRequestActions[models.ProcurementRequest]'
    quote: 'actions.QuoteActions[models.Quote]'
    payment: 'actions.PaymentActions[models.Payment]'
    auditlog: 'actions.AuditLogActions[models.AuditLog]'
    emailthread: 'actions.EmailThreadActions[models.EmailThread]'
    emailmessage: 'actions.EmailMessageActions[models.EmailMessage]'
    workflowexecution: 'actions.WorkflowExecutionActions[models.WorkflowExecution]'

    __slots__ = (
        'organization',
        'user',
        'vendor',
        'procurementrequest',
        'quote',
        'payment',
        'auditlog',
        'emailthread',
        'emailmessage',
        'workflowexecution',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.organization = actions.OrganizationActions[models.Organization](self, models.Organization)
        self.user = actions.UserActions[models.User](self, models.User)
        self.vendor = actions.VendorActions[models.Vendor](self, models.Vendor)
        self.procurementrequest = actions.ProcurementRequestActions[models.ProcurementRequest](self, models.ProcurementRequest)
        self.quote = actions.QuoteActions[models.Quote](self, models.Quote)
        self.payment = actions.PaymentActions[models.Payment](self, models.Payment)
        self.auditlog = actions.AuditLogActions[models.AuditLog](self, models.AuditLog)
        self.emailthread = actions.EmailThreadActions[models.EmailThread](self, models.EmailThread)
        self.emailmessage = actions.EmailMessageActions[models.EmailMessage](self, models.EmailMessage)
        self.workflowexecution = actions.WorkflowExecutionActions[models.WorkflowExecution](self, models.WorkflowExecution)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/home/aparna/Desktop/supplygraph_mvp/apps/ai-service/schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    organization: 'OrganizationBatchActions'
    user: 'UserBatchActions'
    vendor: 'VendorBatchActions'
    procurementrequest: 'ProcurementRequestBatchActions'
    quote: 'QuoteBatchActions'
    payment: 'PaymentBatchActions'
    auditlog: 'AuditLogBatchActions'
    emailthread: 'EmailThreadBatchActions'
    emailmessage: 'EmailMessageBatchActions'
    workflowexecution: 'WorkflowExecutionBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.organization = OrganizationBatchActions(self)
        self.user = UserBatchActions(self)
        self.vendor = VendorBatchActions(self)
        self.procurementrequest = ProcurementRequestBatchActions(self)
        self.quote = QuoteBatchActions(self)
        self.payment = PaymentBatchActions(self)
        self.auditlog = AuditLogBatchActions(self)
        self.emailthread = EmailThreadBatchActions(self)
        self.emailmessage = EmailMessageBatchActions(self)
        self.workflowexecution = WorkflowExecutionBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class OrganizationBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.OrganizationCreateInput,
        include: Optional[types.OrganizationInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Organization,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.OrganizationCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Organization,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.OrganizationWhereUniqueInput,
        include: Optional[types.OrganizationInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Organization,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.OrganizationUpdateInput,
        where: types.OrganizationWhereUniqueInput,
        include: Optional[types.OrganizationInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Organization,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.OrganizationWhereUniqueInput,
        data: types.OrganizationUpsertInput,
        include: Optional[types.OrganizationInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Organization,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.OrganizationUpdateManyMutationInput,
        where: types.OrganizationWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Organization,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.OrganizationWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Organization,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class VendorBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.VendorCreateInput,
        include: Optional[types.VendorInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Vendor,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.VendorCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Vendor,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.VendorWhereUniqueInput,
        include: Optional[types.VendorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Vendor,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.VendorUpdateInput,
        where: types.VendorWhereUniqueInput,
        include: Optional[types.VendorInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Vendor,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.VendorWhereUniqueInput,
        data: types.VendorUpsertInput,
        include: Optional[types.VendorInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Vendor,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.VendorUpdateManyMutationInput,
        where: types.VendorWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Vendor,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.VendorWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Vendor,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class ProcurementRequestBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.ProcurementRequestCreateInput,
        include: Optional[types.ProcurementRequestInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.ProcurementRequest,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.ProcurementRequestCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.ProcurementRequest,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.ProcurementRequestWhereUniqueInput,
        include: Optional[types.ProcurementRequestInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.ProcurementRequest,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.ProcurementRequestUpdateInput,
        where: types.ProcurementRequestWhereUniqueInput,
        include: Optional[types.ProcurementRequestInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.ProcurementRequest,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.ProcurementRequestWhereUniqueInput,
        data: types.ProcurementRequestUpsertInput,
        include: Optional[types.ProcurementRequestInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.ProcurementRequest,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.ProcurementRequestUpdateManyMutationInput,
        where: types.ProcurementRequestWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.ProcurementRequest,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.ProcurementRequestWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.ProcurementRequest,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class QuoteBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.QuoteCreateInput,
        include: Optional[types.QuoteInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Quote,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.QuoteCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Quote,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.QuoteWhereUniqueInput,
        include: Optional[types.QuoteInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Quote,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.QuoteUpdateInput,
        where: types.QuoteWhereUniqueInput,
        include: Optional[types.QuoteInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Quote,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.QuoteWhereUniqueInput,
        data: types.QuoteUpsertInput,
        include: Optional[types.QuoteInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Quote,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.QuoteUpdateManyMutationInput,
        where: types.QuoteWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Quote,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.QuoteWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Quote,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PaymentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PaymentCreateInput,
        include: Optional[types.PaymentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Payment,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PaymentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Payment,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PaymentWhereUniqueInput,
        include: Optional[types.PaymentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Payment,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PaymentUpdateInput,
        where: types.PaymentWhereUniqueInput,
        include: Optional[types.PaymentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Payment,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PaymentWhereUniqueInput,
        data: types.PaymentUpsertInput,
        include: Optional[types.PaymentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Payment,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PaymentUpdateManyMutationInput,
        where: types.PaymentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Payment,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PaymentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Payment,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AuditLogBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AuditLogCreateInput,
        include: Optional[types.AuditLogInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.AuditLog,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AuditLogCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.AuditLog,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AuditLogWhereUniqueInput,
        include: Optional[types.AuditLogInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.AuditLog,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AuditLogUpdateInput,
        where: types.AuditLogWhereUniqueInput,
        include: Optional[types.AuditLogInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.AuditLog,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AuditLogWhereUniqueInput,
        data: types.AuditLogUpsertInput,
        include: Optional[types.AuditLogInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.AuditLog,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AuditLogUpdateManyMutationInput,
        where: types.AuditLogWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.AuditLog,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AuditLogWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.AuditLog,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class EmailThreadBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.EmailThreadCreateInput,
        include: Optional[types.EmailThreadInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.EmailThread,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.EmailThreadCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.EmailThread,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.EmailThreadWhereUniqueInput,
        include: Optional[types.EmailThreadInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.EmailThread,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.EmailThreadUpdateInput,
        where: types.EmailThreadWhereUniqueInput,
        include: Optional[types.EmailThreadInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.EmailThread,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.EmailThreadWhereUniqueInput,
        data: types.EmailThreadUpsertInput,
        include: Optional[types.EmailThreadInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.EmailThread,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.EmailThreadUpdateManyMutationInput,
        where: types.EmailThreadWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.EmailThread,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.EmailThreadWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.EmailThread,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class EmailMessageBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.EmailMessageCreateInput,
        include: Optional[types.EmailMessageInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.EmailMessage,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.EmailMessageCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.EmailMessage,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.EmailMessageWhereUniqueInput,
        include: Optional[types.EmailMessageInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.EmailMessage,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.EmailMessageUpdateInput,
        where: types.EmailMessageWhereUniqueInput,
        include: Optional[types.EmailMessageInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.EmailMessage,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.EmailMessageWhereUniqueInput,
        data: types.EmailMessageUpsertInput,
        include: Optional[types.EmailMessageInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.EmailMessage,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.EmailMessageUpdateManyMutationInput,
        where: types.EmailMessageWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.EmailMessage,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.EmailMessageWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.EmailMessage,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class WorkflowExecutionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.WorkflowExecutionCreateInput,
        include: Optional[types.WorkflowExecutionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.WorkflowExecution,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.WorkflowExecutionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.WorkflowExecution,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.WorkflowExecutionWhereUniqueInput,
        include: Optional[types.WorkflowExecutionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.WorkflowExecution,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.WorkflowExecutionUpdateInput,
        where: types.WorkflowExecutionWhereUniqueInput,
        include: Optional[types.WorkflowExecutionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.WorkflowExecution,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.WorkflowExecutionWhereUniqueInput,
        data: types.WorkflowExecutionUpsertInput,
        include: Optional[types.WorkflowExecutionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.WorkflowExecution,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.WorkflowExecutionUpdateManyMutationInput,
        where: types.WorkflowExecutionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.WorkflowExecution,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.WorkflowExecutionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.WorkflowExecution,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma