# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class UserRole(StrEnum):
    OWNER = 'OWNER'
    ADMIN = 'ADMIN'
    MEMBER = 'MEMBER'
    VIEWER = 'VIEWER'

class RequestStatus(StrEnum):
    CREATED = 'CREATED'
    QUOTES_REQUESTED = 'QUOTES_REQUESTED'
    QUOTES_RECEIVED = 'QUOTES_RECEIVED'
    UNDER_REVIEW = 'UNDER_REVIEW'
    APPROVED = 'APPROVED'
    PAYMENT_PENDING = 'PAYMENT_PENDING'
    PAID = 'PAID'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'

class RequestPriority(StrEnum):
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    URGENT = 'URGENT'

class QuoteSource(StrEnum):
    EMAIL = 'EMAIL'
    UPLOAD = 'UPLOAD'
    MANUAL = 'MANUAL'
    API = 'API'

class QuoteStatus(StrEnum):
    PENDING = 'PENDING'
    REVIEWED = 'REVIEWED'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'

class PaymentStatus(StrEnum):
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'
    REFUNDED = 'REFUNDED'

class WorkflowStatus(StrEnum):
    PENDING = 'PENDING'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'

