from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Organization',
    'User',
    'Vendor',
    'ProcurementRequest',
    'Quote',
    'Payment',
    'AuditLog',
    'EmailThread',
    'EmailMessage',
    'WorkflowExecution',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Organization': {
        'users': 'User',
        'vendors': 'Vendor',
        'requests': 'ProcurementRequest',
        'quotes': 'Quote',
        'payments': 'Payment',
        'auditLogs': 'AuditLog',
    },
    'User': {
        'organization': 'Organization',
        'createdRequests': 'ProcurementRequest',
        'auditLogs': 'AuditLog',
    },
    'Vendor': {
        'organization': 'Organization',
        'quotes': 'Quote',
    },
    'ProcurementRequest': {
        'organization': 'Organization',
        'creator': 'User',
        'quotes': 'Quote',
        'payments': 'Payment',
        'auditLogs': 'AuditLog',
    },
    'Quote': {
        'organization': 'Organization',
        'request': 'ProcurementRequest',
        'vendor': 'Vendor',
        'payments': 'Payment',
    },
    'Payment': {
        'organization': 'Organization',
        'request': 'ProcurementRequest',
        'quote': 'Quote',
    },
    'AuditLog': {
        'organization': 'Organization',
        'user': 'User',
        'request': 'ProcurementRequest',
    },
    'EmailThread': {
        'messages': 'EmailMessage',
    },
    'EmailMessage': {
        'thread': 'EmailThread',
    },
    'WorkflowExecution': {
    },
}

# fmt: on